#!/bin/bash

wget https://prote.ua/index.php?route=feed/google_sitemap --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapc.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapc.xml.draft
minimumsize=50
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapc.xml.draft /var/www/prote/data/www/prote.ua/sitemapc.xml
else
    echo size is under $minimumsize kilobytes
fi

#file=/var/www/prote/data/www/prote.ua/sitemapi.xml.draft
#minimumsize=90
#actualsize=$(du -k "$file" | cut -f 1)
#if [ $actualsize -ge $minimumsize ]; then
#    cp -f /var/www/prote/data/www/prote.ua/sitemapi.xml.draft /var/www/prote/data/www/prote.ua/sitemapi.xml
#else
#    echo size is under $minimumsize kilobytes
#fi

exit

php /var/www/prote/data/www/prote.ua/exec/te.php

php /var/www/prote/data/www/prote.ua/exec/tee.php


wget https://prote.ua/index.php?route=feed/google_sitemap/brands --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapb.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapb.xml.draft
minimumsize=90
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapb.xml.draft /var/www/prote/data/www/prote.ua/sitemapb.xml
else
    echo size is under $minimumsize kilobytes
fi

wget https://prote.ua/index.php?route=feed/google_sitemap/other --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapo.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapo.xml.draft
minimumsize=1
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapo.xml.draft /var/www/prote/data/www/prote.ua/sitemapo.xml
else
    echo size is under $minimumsize kilobytes
fi

wget https://prote.ua/index.php?route=feed/google_sitemap/filters\&part=0 --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapf0.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapf0.xml.draft
minimumsize=90
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapf0.xml.draft /var/www/prote/data/www/prote.ua/sitemapf0.xml
else
    echo size is under $minimumsize kilobytes
fi


wget https://prote.ua/index.php?route=feed/google_sitemap/filters\&part=1 --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapf1.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapf1.xml.draft
minimumsize=90
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapf1.xml.draft /var/www/prote/data/www/prote.ua/sitemapf1.xml
else
    echo size is under $minimumsize kilobytes
fi


wget https://prote.ua/index.php?route=feed/google_sitemap/filters\&part=2 --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapf2.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapf2.xml.draft
minimumsize=90
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapf2.xml.draft /var/www/prote/data/www/prote.ua/sitemapf2.xml
else
    echo size is under $minimumsize kilobytes
fi


wget https://prote.ua/index.php?route=feed/google_sitemap/filters\&part=3 --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemapf3.xml.draft
file=/var/www/prote/data/www/prote.ua/sitemapf3.xml.draft
minimumsize=90
actualsize=$(du -k "$file" | cut -f 1)
if [ $actualsize -ge $minimumsize ]; then
    cp -f /var/www/prote/data/www/prote.ua/sitemapf3.xml.draft /var/www/prote/data/www/prote.ua/sitemapf3.xml
else
    echo size is under $minimumsize kilobytes
fi


wget https://prote.ua/index.php?route=feed/google_sitemap/mapindex --no-check-certificate -O /var/www/prote/data/www/prote.ua/sitemap.xml
